version: 2
updates:
  # 🔹 Met à jour tes dépendances npm (package.json / package-lock.json)
  - package-ecosystem: "npm"
    directory: "/"          # "/" = à la racine de ton projet
    schedule:
      interval: "weekly"    # vérifie chaque semaine
      day: "monday"         # (optionnel) fait la vérif le lundi
      time: "04:00"         # (optionnel) heure UTC

  # 🔹 Met à jour tes GitHub Actions (si tu as des workflows dans .github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
